name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Soketi Version'
        required: true
        type: string

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Setup Node.js v${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Execute lint & build
        run: |
          pnpm run lint
          pnpm run build

      - uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  docker:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, debian]
        include:
          - distro: alpine
            dockerfile: Dockerfile
          - distro: debian
            dockerfile: Dockerfile.debian
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: phillarmonic/soketi
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            suffix=-${{ matrix.distro }}
          labels: |
            org.opencontainers.image.authors="Soketi <open-source@soketi.app> & Phillarmonic Software"
            org.opencontainers.image.source=https://github.com/soketi/soketi
            org.opencontainers.image.url=https://soketi.app
            org.opencontainers.image.documentation=https://docs.soketi.app
            org.opencontainers.image.vendor=Soketi
            org.opencontainers.image.licenses=AGPL-3.0
            org.opencontainers.image.version=${{ inputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            phillarmonic/soketi:${{ inputs.version }}-${{ matrix.distro }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SOKETI_VERSION=${{ inputs.version }}
